#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check if a merge or cherry-pick is in progress
if git rev-parse --verify MERGE_HEAD >/dev/null 2>&1 && [ -z "$(git status --porcelain)" ]; then
  echo "A merge is in progress, hook skipped."
elif git rev-parse --verify CHERRY_PICK_HEAD >/dev/null 2>&1; then
  echo "A cherry-pick is in progress, hook skipped."
else
  exec < /dev/tty && node_modules/.bin/cz --hook || true
fi

exit 0
